services:
  - type: web
    name: thinclient-rust-backend
    env: docker
    region: frankfurt
    plan: free
    dockerContext: server/
    dockerfilePath: server/Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
        generateValue: true
      - key: TURN_SECRET
        generateValue: true
      - key: TURN_URL
        value: "turn:openrelay.metered.ca:80"

  - type: web
    name: thinclient-turn-server
    env: docker
    region: frankfurt
    plan: free
    dockerContext: turn-server/
    dockerfilePath: turn-server/Dockerfile
    envVars:
      - key: PORT
        value: "3478"
