[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["ws", "macros"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tokio = { version = "1.37", features = ["full"] }
tokio-websockets = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libsql = "0.3"

uuid = { version = "1.8", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
jsonwebtoken = "9.3"
time = { version = "0.3", features = ["serde", "serde-well-known", "formatting"] }
rustls = "0.23"
dotenvy = "0.15"
anyhow = "1.0"
futures = "0.3"
chrono = "0.4.45"
tokio-util = { version = "0.7.19", features = ["codec"] }
bytes = "1.12.1"
hmac = "0.12"
sha1 = "0.10"
base64 = "0.22"

[dev-dependencies]
futures-util = "0.3.34"
http = "1.5.0"
reqwest = { version = "0.13.5", features = ["json"] }
tokio-tungstenite = "0.30.0"
